//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiplomProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class catalogue
    {
        public int catalogid { get; set; }
        public string catalogname { get; set; }
        public string catalogimagepath { get; set; }
        public string catalogdesc { get; set; }
    }
}
