//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiplomProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class requests
    {
        public int requestid { get; set; }
        public int status { get; set; }
        public string requestdesc { get; set; }
        public string requestfiles { get; set; }
    
        public virtual requeststatus requeststatus { get; set; }
    }
}
