//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiplomProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class roleusers
    {
        public int users { get; set; }
        public Nullable<int> roles { get; set; }
    
        public virtual roles roles1 { get; set; }
        public virtual users users1 { get; set; }
    }
}
